parameters:
- name: terraformVersion
  type: string

- name: workingDirectory
  type: string

- name: azureServiceConnection
  type: string

jobs:

- job: Apply
  displayName: Terraform Apply

  steps:

  - checkout: self
    clean: true

  # Install Terraform
  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  # Configure Plugin Cache
  - script: |
      mkdir -p ~/.terraform.d/plugin-cache

      cat > ~/.terraformrc <<EOF
      plugin_cache_dir="$HOME/.terraform.d/plugin-cache"
      EOF
    displayName: Configure Terraform Plugin Cache

  # Restore Cache
  - task: Cache@2
    displayName: Restore Terraform Provider Cache
    inputs:
      key: terraform | "$(Agent.OS)" | ${{ parameters.workingDirectory }}/.terraform.lock.hcl
      restoreKeys: |
        terraform | "$(Agent.OS)"
      path: ~/.terraform.d/plugin-cache

  # Download Plan Artifact
  - task: DownloadPipelineArtifact@2
    displayName: Download Terraform Plan
    inputs:
      artifact: terraform-plan
      path: $(Pipeline.Workspace)/terraform-plan

  # Terraform Init
  - task: AzureCLI@2
    displayName: Terraform Init
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e

        cd $(Pipeline.Workspace)/terraform-plan

        terraform init \
          -backend-config=backend.hcl

  # Terraform Apply
  - task: AzureCLI@2
    displayName: Terraform Apply
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e

        cd $(Pipeline.Workspace)/terraform-plan

        terraform apply \
          -lock=true \
          -auto-approve \
          tfplan.binary