parameters:
- name: terraformVersion
  type: string

- name: workingDirectory
  type: string

- name: azureServiceConnection
  type: string

- name: keyVaultName
  type: string

- name: infracostSecret
  type: string

jobs:

- job: Plan
  displayName: Terraform Plan

  steps:

  - checkout: self
    clean: true

  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  - script: |
      mkdir -p ~/.terraform.d/plugin-cache

      cat > ~/.terraformrc <<EOF
      plugin_cache_dir="$HOME/.terraform.d/plugin-cache"
      EOF
    displayName: Configure Terraform Plugin Cache

  - task: Cache@2
    displayName: Restore Terraform Provider Cache
    inputs:
      key: terraform | "$(Agent.OS)" | ${{ parameters.workingDirectory }}/.terraform.lock.hcl
      restoreKeys: |
        terraform | "$(Agent.OS)"
      path: ~/.terraform.d/plugin-cache

  - task: AzureCLI@2
    displayName: Terraform Init
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e

        cd ${{ parameters.workingDirectory }}

        terraform init \
          -backend-config=backend.hcl

  - task: AzureCLI@2
    displayName: Terraform Plan
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e

        cd ${{ parameters.workingDirectory }}

        terraform plan \
          -lock=true \
          -out=tfplan.binary

        terraform show -json tfplan.binary > plan.json

  - task: AzureKeyVault@2
    displayName: Retrieve Infracost API Key
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      KeyVaultName: ${{ parameters.keyVaultName }}
      SecretsFilter: ${{ parameters.infracostSecret }}

  - script: |
      curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
    displayName: Install Infracost

  - script: |
      set -e

      cd ${{ parameters.workingDirectory }}

      infracost breakdown \
        --path plan.json \
        --format table
    displayName: Infracost Cost Estimate
    env:
      INFRACOST_API_KEY: $(INFRACOST-API-KEY)

  - task: PublishPipelineArtifact@1
    displayName: Publish Terraform Plan
    inputs:
      targetPath: ${{ parameters.workingDirectory }}
      artifact: terraform-plan