parameters:
  - name: terraformVersion
    type: string

  - name: azureServiceConnection
    type: string

  - name: workingDirectory
    type: string

stages:
- stage: Validate
  displayName: "Terraform Validate"

  jobs:
  - job: Validate
    displayName: "Validate Terraform"

    steps:

    - checkout: self
      clean: true

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: ${{ parameters.terraformVersion }}

    - task: Cache@2
      displayName: Cache Terraform Providers
      inputs:
        key: 'terraform | "$(Agent.OS)" | ${{ parameters.workingDirectory }}/.terraform.lock.hcl'
        restoreKeys: |
          terraform | "$(Agent.OS)"
        path: $(Pipeline.Workspace)/.terraform.d/plugin-cache

    - script: |
        mkdir -p $(Pipeline.Workspace)/.terraform.d/plugin-cache

        cat > ~/.terraformrc <<EOF
        plugin_cache_dir = "$(Pipeline.Workspace)/.terraform.d/plugin-cache"
        EOF
      displayName: Configure Terraform Plugin Cache

    - task: AzureCLI@2
      displayName: Terraform Init
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: ${{ parameters.workingDirectory }}
        inlineScript: |
          terraform init \
            -reconfigure \
            -backend-config=backend.hcl \
            -input=false

    - script: terraform fmt -check -recursive
      displayName: Terraform Format Check
      workingDirectory: ${{ parameters.workingDirectory }}

    - script: terraform validate
      displayName: Terraform Validate
      workingDirectory: ${{ parameters.workingDirectory }}