trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - workloads/ai-assistant/**
      - pipelines/azure-cicd-ai-assistant.yml
    exclude:
      - '**/*.md'

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - workloads/ai-assistant/**
      - pipelines/azure-cicd-ai-assistant.yml
    exclude:
      - '**/*.md'

variables:
  - name: terraformVersion
    value: '1.15.8'

  - name: azureServiceConnection
    value: 'app-prod'

  - name: workingDirectory
    value: 'workloads/ai-assistant'

pool:
  vmImage: ubuntu-latest

stages:

- template: templates/plan.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)

- template: templates/apply.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)
    environmentName: 'ai-assistant-prod'
