trigger:
  branches:
    include:
      - develop
      - main

pr:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.15.8'
  workingDirectory: 'environments/bootstrap'
  azureServiceConnection: 'bootstrap'
  keyVaultName: 'kv-ht-boot-cin-01'
  infracostSecret: 'INFRACOST-API-KEY'

stages:

- template: templates/validate.yml
  parameters:
    terraformVersion: $(terraformVersion)
    workingDirectory: $(workingDirectory)
    azureServiceConnection: $(azureServiceConnection)

- template: templates/plan.yml
  parameters:
    terraformVersion: $(terraformVersion)
    workingDirectory: $(workingDirectory)
    azureServiceConnection: $(azureServiceConnection)
    keyVaultName: $(keyVaultName)
    infracostSecret: $(infracostSecret)

- template: templates/apply.yml
  parameters:
    terraformVersion: $(terraformVersion)
    workingDirectory: $(workingDirectory)
    azureServiceConnection: $(azureServiceConnection)