trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.15.8'
  keyVaultName: 'kv-ht-boot-cin-01'
  secretName: 'INFRACOST_CLI_AUTHENTICATION_TOKEN'

steps:
- checkout: self

# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '$(terraformVersion)'

# Clean cache
- script: rm -rf .terraform .terraform.lock.hcl
  displayName: 'Clean Terraform cache'
  workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap

# Init + validate
- script: |
    terraform init -backend-config=backend.hcl
    terraform validate
  displayName: 'Terraform Init & Validate'
  workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap

# Fetch Infracost token
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'bootstrap'
    KeyVaultName: '$(keyVaultName)'
    SecretsFilter: '$(secretName)'

# Infracost estimate
- script: |
    curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
    terraform plan -out tfplan.binary
    terraform show -json tfplan.binary > plan.json
    infracost breakdown --path plan.json \
      --api-key $(INFRACOST_CLI_AUTHENTICATION_TOKEN) \
      --format table
  displayName: 'Infracost Estimate'
  workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap

# Apply only on main
- script: terraform apply -auto-approve tfplan.binary
  displayName: 'Terraform Apply'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  workingDirectory: $(System.DefaultWorkingDirectory)/bootstrap
