trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.15.8'
  keyVaultName: 'kv-ht-boot-cin-01'
  secretName: 'INFRACOST-API-KEY'

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '$(terraformVersion)'

  - script: |
      terraform init
      terraform validate
    displayName: 'Terraform Validate'

  # Fetch Infracost API key securely from Key Vault
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'bootstrap'
      KeyVaultName: '$(keyVaultName)'
      SecretsFilter: '$(secretName)'

  - script: |
      curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
      infracost breakdown --path . \
        --api-key $(INFRACOST-API-KEY) \
        --format table
    displayName: 'Infracost Estimate'

  # Apply only on main branch
  - script: |
      terraform apply -auto-approve
    displayName: 'Terraform Apply'