trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - platform/shared-services/**
      - pipelines/azure-cicd-shared-ser.yml
    exclude:
      - '**/*.md'

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - platform/shared-services/**
      - pipelines/azure-cicd-shared-ser.yml
    exclude:
      - '**/*.md'

variables:
  - name: terraformVersion
    value: '1.15.8'

  - name: azureServiceConnection
    value: 'shared-services'

  - name: workingDirectory
    value: 'platform/shared-services'


pool:
  vmImage: ubuntu-latest

stages:

- template: templates/plan.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)

- template: templates/apply.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)
    environmentName: 'shared-services-prod'
