trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

variables:
  - name: terraformVersion
    value: '1.15.8'

  - name: azureServiceConnection
    value: 'shared-services'

  - name: workingDirectory
    value: 'environments/shared-services'

  #- name: applyBranch
   # value: 'refs/heads/develop'

pool:
  vmImage: ubuntu-latest

stages:

- template: templates/validate.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)

- template: templates/plan.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)

- template: templates/apply.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)
    #applyBranch: $(applyBranch)
