trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

variables:
  - name: terraformVersion
    value: '1.15.8'

  - name: azureServiceConnection
    value: 'shared-services'

  - name: workingDirectory
    value: 'environments/shared-services'

  - name: applyBranch
    value: 'refs/heads/main'

pool:
  vmImage: ubuntu-latest

stages:

- template: ../../pipelines/templates/validate.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)

- template: ../../pipelines/templates/plan.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)

- template: ../../pipelines/templates/apply.yml
  parameters:
    terraformVersion: $(terraformVersion)
    azureServiceConnection: $(azureServiceConnection)
    workingDirectory: $(workingDirectory)
    applyBranch: $(applyBranch)
